config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  resources :coins

  root "welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @nome = params[:nome]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_br(date_us)
    date_us.strftime("%d/%m/%Y")
  end

  def ambiente_rails
    if Rails.env.development?
      "Desenvolvimento"
    elsif Rails.env.production?
      "Produção"
    else
      "Teste"
    end
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <p>
    <strong>Descrição:</strong>
    <%= coin.description %>
  </p>

  <p>
    <strong>Acronimo:</strong>
    <%= coin.acronym %>
  </p>

  <p>
    <strong>Url Imagem:</strong>
    <%= coin.url_image %>
  </p>
</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> proibiu que esta moeda fosse salva:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "field">
    <div>
      <%= form.label "Nome", style: "display: block" %>
      <%= form.text_field :description %>
    </div>

    <div>
      <%= form.label "Sigla", style: "display: block" %>
      <%= form.text_field :acronym %>
    </div>

    <div>
      <%= form.label "Link da imagem", style: "display: block" %>
      <%= form.text_field :url_image %>    
    </div>

    <div>
      <% if coin.url_image.present? %>
        <%= image_tag coin.url_image, width: 25, height: 25 %>
      <% else %>
        <p>Imagem não disponível</p>
      <% end %>
    </div>
  </div>

  <div class= "actions">
    <%= form.submit "Atualizar" %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editando Moeda</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Detalhes desta moeda", @coin %> |
  <%= link_to "Voltar para moedas", coins_path %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Moedas</h1>

<table>
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Sigla</th>      
      <th>Imagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>        
        <td>
          <% if coin.url_image.present? %>
            <%= image_tag coin.url_image, width: 25, height: 25 %>
          <% else %>
            <p>Imagem não disponível</p>
          <% end %>
        </td>
        <td><%= link_to "Detalhes", coin %></td>
        <td><%= link_to "Editar", edit_coin_path(coin) %></td>
        <td><%= link_to "Apagar", coin, method: :delete, data: { confirm: "Tem certeza?" } %></td>
      </tr>
    <% end %>
  </tbody>  
</table>  
<%= link_to "Criar Moeda", new_coin_path %>
<%= link_to "Voltar", root_path %>


<!-- <div id="coins">
  <% @coins.each do |coin| %>
    <%= render coin %>
    <p>
      <%= link_to "Show this coin", coin %>
    </p>
  <% end %>
</div>

<%= link_to "New coin", new_coin_path %>

app/views/coins/new.html.erb
<h1>Nova Moeda</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Voltar às moedas", coins_path %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div>
    <% if @coin.url_image.present? %>
      <%= image_tag @coin.url_image, width: 25, height: 25 %>
    <% else %>
      <p>Imagem não disponível</p>
    <% end %>
  </div>

<div>
  <%= link_to "Edite esta moeda", edit_coin_path(@coin) %> |
  <%= link_to "Voltar às moedas", coins_path %>
  
  <%= button_to "Destrua esta moeda", @coin, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto Wallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/_menu.html.erb
<ul>   
    <li>
        <%= link_to "Todas Moedas", "/coins" %>
    </li>
</ul> 

app/views/welcome/index.html.erb
<h1>Seja Bem-Vindo</h1>

<p><strong>Data: </strong><%= date_br(Date.today) %>

<%= render "menu" %>

<p>
    Você esta en um ambiente de <strong><%= Rails.env %></strong>
</p>


<!-- 

    Alguns comandos/dicas do Ruby

<p>Uma simples soma: <%= 12 + 8 %></p>

<p>Meu nome invertido é: <%= "Douglas Marins Vitoriano".reverse %></p>

<p>Meu nome tem <%= "Douglas Marins Vitoriano".length %> caracteres</p>
<p>A data de hoje é: <%= Date.today.strftime("%d/%m/%Y") %></p> 


    <li>
        <a href= "/coins">Cadastro de Moedas</a> visão de html e o de cima é o de ruby
    </li> 
-->